import { PropsWithChildren } from "react";
import { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className="bg-background text-foreground antialiased"
        style={poppins.style}
      >
        {props.children}
      </body>
    </html>
  );
}
